version: 2
jobs:
  build:
    docker:
     - image: circleci/node:14
    branches:
      only:
        - main
    steps:
      - checkout
      - run: echo "Hello Circle ci"
      - run: npm -v
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - run:
          name: deploy
          command: curl -X POST $VERCEL_HOOK_URL
          